columns:
  '#assembly_accession': str
  'refseq_category': str
  'taxid': str
  'organism_name': str
  'infraspecific_name': str
  'assembly_level': str
  'seq_rel_date': str
  'ftp_path': str

assembly_level:
  - 'Complete Genome'
  - 'Chromosome'
  - 'Scaffold'
  - 'Contig'

refseq_category:
  - 'reference genome'
  - 'representative genome'
  - 'na'